### ISSUE TITLE
please add support of timeout expiration option

### ISSUE THREAD

**Issue by bobagold** [VeliovGroup/Client-Storage#2] opened 2017-09-08 12:39 UTC
it can be useful to set some key-value pair for limited time, for example, 1 hour or 1 day

**Comment by dr-dimitru** [comment] 2019-05-22 08:52
Hello @bobagold ,

Thank you for this request, I know it took years to implement it 🤦‍♂️ , final solution released as [`v3.0.0`](https://github.com/VeliovGroup/Client-Storage/releases/tag/3.0.0).
Let me know wdyt. Feel free to reopen it in case if the issue is still persists on your end.

**Closed as completed by dr-dimitru** 2019-05-22 08:52 UTC
Labels: enhancement
